(function () {
  "use strict";

  // ════════════════════════════════════════════════════════════
  //  KATY MOVERS — business knowledge base
  //  In production, these facts come from the business's settings
  //  in the dashboard, and the chat answers are generated by a real
  //  AI call to the backend (/api/chat) using this same data as context.
  //  For the demo, answers are matched from these facts directly.
  // ════════════════════════════════════════════════════════════
  var BIZ = {
    name: "Katy Movers, Inc.",
    phone: "281-391-3536",
    phoneHref: "tel:2813913536",
    serviceArea: "Katy and the greater Houston area — including Cypress, Sugar Land, Richmond, Fulshear, Brookshire, and most of the Houston metro.",
    hours: "Our office is open Monday through Saturday, with moves scheduled 7 days a week depending on availability.",
    founded: "1996 — nearly 30 years serving Houston families.",
    licensed: "Yes — fully licensed (TxDMV No. 005644137C) and insured.",
    specialties: "Residential, piano, and commercial moves, plus full packing services. Pianos are our specialty — 30 years of experience with baby grand, upright, and organ.",
    pricing: "Most quotes are priced on your inventory, conditions, and distance, so you know the cost up front with no surprises. No inventory list? We'll quote a fair hourly rate instead.",
    pianos: "Pianos are absolutely our specialty — we've been moving them for 30 years. Baby grand, upright, organ, or any delicate item, we handle it with dedicated equipment.",
  };

  // ── Demo ribbon dismiss ──
  var ribbon = document.getElementById("demoRibbon");
  var closeRibbon = document.getElementById("closeRibbon");
  if (closeRibbon) closeRibbon.addEventListener("click", function () { ribbon.style.display = "none"; });

  // ── Mobile nav toggle ──
  var mobileToggle = document.getElementById("mobileToggle");
  var mobileNav = document.getElementById("mobileNav");
  if (mobileToggle && mobileNav) {
    mobileToggle.addEventListener("click", function () {
      var open = mobileNav.classList.toggle("open");
      mobileToggle.setAttribute("aria-expanded", open ? "true" : "false");
    });
    mobileNav.querySelectorAll("a").forEach(function (a) {
      a.addEventListener("click", function () { mobileNav.classList.remove("open"); mobileToggle.setAttribute("aria-expanded", "false"); });
    });
  }

  // ════════════════════════════════════════════════════════════
  //  QUOTE FLOW
  // ════════════════════════════════════════════════════════════
  var steps = {
    intro: document.querySelector('[data-step="intro"]'),
    form: document.querySelector('[data-step="form"]'),
    result: document.querySelector('[data-step="result"]'),
  };
  function showStep(name) { Object.keys(steps).forEach(function (k) { steps[k].hidden = k !== name; }); }

  var chat = document.getElementById("aiChat");
  function addBotMessage(text) {
    var msg = document.createElement("div");
    msg.className = "ai-msg ai-msg--bot";
    var p = document.createElement("p"); p.textContent = text; msg.appendChild(p);
    chat.appendChild(msg);
  }

  document.getElementById("startQuoteBtn").addEventListener("click", function () {
    addBotMessage("Great — let's get your details. This takes about 60 seconds.");
    showStep("form");
    document.getElementById("firstName").focus();
  });
  document.getElementById("resetQuoteBtn").addEventListener("click", function () {
    document.getElementById("quoteForm").reset();
    showStep("intro");
    chat.querySelectorAll(".ai-msg--bot").forEach(function (m, i) { if (i > 0) m.remove(); });
  });

  var form = document.getElementById("quoteForm");
  var submitBtn = document.getElementById("submitQuoteBtn");

  form.addEventListener("submit", function (e) {
    e.preventDefault();
    var fd = new FormData(form);
    var payload = {
      firstName: fd.get("firstName"), lastName: fd.get("lastName"),
      phone: fd.get("phone"), email: fd.get("email") || null,
      moveDate: fd.get("moveDate"), homeSize: fd.get("homeSize"),
      originZip: fd.get("originZip"), destZip: fd.get("destZip"),
      specialItems: fd.getAll("specialItems"), howHeard: fd.get("howHeard") || null,
      source: "website_widget", businessSlug: "katy-movers-demo",
    };
    submitBtn.disabled = true;
    submitBtn.innerHTML = '<i class="ti ti-loader-2" aria-hidden="true"></i> Calculating your estimate…';
    fetch("/api/quote", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) })
      .then(function (r) { if (!r.ok) throw new Error(); return r.json(); })
      .then(function (data) { renderResult(data); showStep("result"); })
      .catch(function () { renderError(); showStep("result"); })
      .finally(function () { submitBtn.disabled = false; submitBtn.innerHTML = '<i class="ti ti-bolt" aria-hidden="true"></i> Get my fast estimate'; });
  });

  function fmtMoney(n) { return "$" + Number(n).toLocaleString("en-US"); }
  function fmtDate(iso) { if (!iso) return "—"; var d = new Date(iso + "T00:00:00"); return d.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" }); }

  function renderResult(data) {
    var card = document.getElementById("resultCard");
    var items = data.specialItems && data.specialItems.length ? data.specialItems.join(", ") : "None reported";
    var distance = data.moveType === "long-distance" ? "Long-distance move" : "Local move";
    card.innerHTML =
      '<div class="result-card__header"><div class="result-card__check"><i class="ti ti-check" aria-hidden="true"></i></div>' +
      '<div><h4>You\u2019re all set, ' + esc(data.firstName) + '!</h4><p>Quote #' + esc(String(data.leadId)) + ' \u00b7 our team will follow up fast</p></div></div>' +
      '<div class="result-stat"><p class="result-stat__label">Estimated cost</p><p class="result-stat__value">' + fmtMoney(data.estimate.low) + '\u2013' + fmtMoney(data.estimate.high) + '<span> total</span></p></div>' +
      '<div class="result-grid">' +
      '<div class="result-cell"><p class="result-cell__label">Move date</p><p class="result-cell__value">' + fmtDate(data.moveDate) + '</p></div>' +
      '<div class="result-cell"><p class="result-cell__label">Move type</p><p class="result-cell__value">' + distance + '</p></div>' +
      '<div class="result-cell"><p class="result-cell__label">Suggested crew</p><p class="result-cell__value">' + esc(data.estimate.crew) + '</p></div>' +
      '<div class="result-cell"><p class="result-cell__label">Suggested truck</p><p class="result-cell__value">' + esc(data.estimate.truck) + '</p></div></div>' +
      '<div class="result-cell" style="margin-bottom:13px;"><p class="result-cell__label">Special items</p><p class="result-cell__value">' + esc(items) + '</p></div>' +
      '<div class="result-note"><i class="ti ti-message-2" aria-hidden="true"></i> A confirmation text is on its way to ' + esc(data.phone) + ' right now — and a team member will call shortly to confirm the details.</div>';
  }
  function renderError() {
    document.getElementById("resultCard").innerHTML =
      '<div class="result-note"><i class="ti ti-alert-triangle" aria-hidden="true"></i> Something went wrong reaching our quote system. Please call us at ' + BIZ.phone + ' — we\u2019ll take care of you right away.</div>';
  }
  function esc(s) { var d = document.createElement("div"); d.textContent = s == null ? "" : s; return d.innerHTML; }

  var moveDateInput = document.getElementById("moveDate");
  if (moveDateInput) moveDateInput.setAttribute("min", new Date().toISOString().split("T")[0]);

  // ════════════════════════════════════════════════════════════
  //  CHATBOT
  // ════════════════════════════════════════════════════════════
  var chatFab = document.getElementById("chatFab");
  var chatWindow = document.getElementById("chatWindow");
  var chatClose = document.getElementById("chatClose");
  var chatBody = document.getElementById("chatBody");
  var chatForm = document.getElementById("chatForm");
  var chatInput = document.getElementById("chatInput");
  var chatQuick = document.getElementById("chatQuick");
  var openChatBtn = document.getElementById("openChatBtn");
  var chatStarted = false;
  var msgCount = 0;

  function openChat() {
    chatWindow.hidden = false;
    chatFab.classList.add("hidden");
    if (!chatStarted) {
      chatStarted = true;
      botSay("Hi there! 👋 I'm here to help with your move. Ask me anything — service area, pricing, pianos, you name it.");
      renderQuickReplies(["What areas do you serve?", "How much does a move cost?", "Do you move pianos?", "Get a quote"]);
    }
    setTimeout(function () { chatInput.focus(); }, 100);
  }
  function closeChat() { chatWindow.hidden = true; chatFab.classList.remove("hidden"); }

  chatFab.addEventListener("click", openChat);
  chatClose.addEventListener("click", closeChat);
  if (openChatBtn) openChatBtn.addEventListener("click", openChat);

  function botSay(text, opts) {
    opts = opts || {};
    var row = document.createElement("div");
    row.className = "chat-msg chat-msg--bot";
    row.innerHTML = '<div class="chat-bubble">' + text + '</div>';
    chatBody.appendChild(row);
    chatBody.scrollTop = chatBody.scrollHeight;
  }
  function userSay(text) {
    var row = document.createElement("div");
    row.className = "chat-msg chat-msg--user";
    row.innerHTML = '<div class="chat-bubble">' + esc(text) + '</div>';
    chatBody.appendChild(row);
    chatBody.scrollTop = chatBody.scrollHeight;
  }
  function typing(cb) {
    var row = document.createElement("div");
    row.className = "chat-msg chat-msg--bot";
    row.innerHTML = '<div class="chat-bubble chat-typing"><span></span><span></span><span></span></div>';
    chatBody.appendChild(row);
    chatBody.scrollTop = chatBody.scrollHeight;
    setTimeout(function () { row.remove(); cb(); }, 650);
  }

  function renderQuickReplies(arr) {
    chatQuick.innerHTML = "";
    arr.forEach(function (q) {
      var b = document.createElement("button");
      b.type = "button"; b.className = "chat-chip"; b.textContent = q;
      b.addEventListener("click", function () { handleUserMessage(q); });
      chatQuick.appendChild(b);
    });
  }

  // Demo answer-matching. In production this is replaced by a real
  // AI call: POST /api/chat with { message, history, businessFacts }.
  function answerFor(raw) {
    var q = raw.toLowerCase();
    if (/area|serve|service|where|location|cover|cypress|sugar|richmond|houston/.test(q))
      return { text: "We serve " + BIZ.serviceArea, quick: ["How much does it cost?", "Get a quote"] };
    if (/price|cost|much|rate|quote|estimate|expensive|charge/.test(q))
      return { text: BIZ.pricing + " Want me to pull up a fast quote for you now?", quick: ["Yes, get a quote", "Do you move pianos?"], offerHuman: true };
    if (/piano|grand|upright|organ/.test(q))
      return { text: BIZ.pianos, quick: ["Get a quote", "What else do you move?"] };
    if (/hour|open|when|time|day|saturday|sunday|weekend/.test(q))
      return { text: BIZ.hours, quick: ["What areas do you serve?", "Get a quote"] };
    if (/licens|insur|legal|bonded|dot|txdmv/.test(q))
      return { text: BIZ.licensed + " You can move with total peace of mind.", quick: ["Get a quote"] };
    if (/year|long|experience|since|established|old/.test(q))
      return { text: "We've been family owned and operated since " + BIZ.founded, quick: ["Get a quote"] };
    if (/commercial|office|business|pack|residential|apartment|what.*move|services/.test(q))
      return { text: BIZ.specialties, quick: ["Get a quote", "Do you move pianos?"] };
    if (/quote|book|schedule|reserve|start/.test(q))
      return { text: "Perfect — let's get you a real estimate. It takes about 60 seconds.", action: "quote" };
    if (/person|human|talk|call|speak|representative|agent|someone/.test(q))
      return { text: "Of course! You can reach our team directly at " + BIZ.phone + ". Want me to have someone call you instead?", offerHuman: true, quick: ["Have someone call me", "Get a quote"] };
    if (/thank|thanks|great|awesome|cool|ok|okay/.test(q))
      return { text: "Happy to help! Anything else I can answer, or shall I get you a quick quote?", quick: ["Get a quote", "What areas do you serve?"] };
    if (/call me|have someone|callback|reach me/.test(q))
      return { text: "You got it. Drop your number in a quick quote and our team will call you fast — usually within minutes during business hours.", action: "quote" };
    return { text: "Good question! For specifics like that, our team can give you the exact answer. You can call us at " + BIZ.phone + ", or I can get you a fast quote to start. What works?", offerHuman: true, quick: ["Get a quote", "Have someone call me"] };
  }

  function handleUserMessage(text) {
    if (!text || !text.trim()) return;
    userSay(text);
    chatQuick.innerHTML = "";
    msgCount++;
    typing(function () {
      var ans = answerFor(text);
      botSay(ans.text);

      // After a couple of exchanges, proactively offer a live person
      if (msgCount >= 3 && !ans.offerHuman && !ans.action) {
        setTimeout(function () {
          typing(function () {
            botSay("By the way — would you rather just talk to a real person? Call us anytime at " + BIZ.phone + ".");
            renderQuickReplies(["Have someone call me", "Get a quote", "I'm good for now"]);
          });
        }, 500);
        return;
      }
      if (ans.action === "quote") {
        setTimeout(function () {
          closeChat();
          document.getElementById("quote").scrollIntoView({ behavior: "smooth", block: "start" });
          document.getElementById("startQuoteBtn").click();
        }, 700);
        return;
      }
      if (ans.quick) renderQuickReplies(ans.quick);
    });
  }

  chatForm.addEventListener("submit", function (e) {
    e.preventDefault();
    var v = chatInput.value;
    chatInput.value = "";
    handleUserMessage(v);
  });

  // ════════════════════════════════════════════════════════════
  //  GOOGLE REVIEWS  (placeholder data for the demo)
  //  In production: GET /api/reviews proxies the Google Places API
  //  (Place Details → reviews) so these are the business's real,
  //  live Google reviews. Same render code, real data.
  // ════════════════════════════════════════════════════════════
  var REVIEWS = [
    { name: "Aurora M.", initial: "A", color: "#c8202e", rating: 5, when: "2 weeks ago", text: "This is the 2nd time they've moved my wife and I — batting 2 for 2. The entire crew was amazing, careful, and fast. Wouldn't use anyone else in Katy." },
    { name: "James R.", initial: "J", color: "#14305f", rating: 5, when: "1 month ago", text: "My husband retired from the Navy and we've been through more moves than I can count. These guys were the best we've ever had. Professional from start to finish." },
    { name: "Linda S.", initial: "L", color: "#2b5cb0", rating: 5, when: "1 month ago", text: "Your guys are work animals! Impressed with their attitude and the care they took with our antiques. Went above and beyond what we expected." },
    { name: "Marcus T.", initial: "M", color: "#a3121e", rating: 5, when: "2 months ago", text: "Moved our baby grand piano without a single scratch. You can tell they've done this for years. The quote was exactly what we paid — no surprises." },
    { name: "Priya K.", initial: "P", color: "#1f4485", rating: 5, when: "2 months ago", text: "Stress-free and pleasant move. The office staff was responsive and the movers were on time and courteous. Highly recommend to anyone in the Houston area." },
    { name: "Daniel W.", initial: "D", color: "#c8202e", rating: 5, when: "3 months ago", text: "We are so happy we chose Katy Movers. Fair pricing, careful handling, and a team that genuinely cared. They made a hard day so much easier." },
  ];

  function starRow(n) {
    var s = "";
    for (var i = 0; i < 5; i++) s += '<i class="ti ti-star-filled" aria-hidden="true"></i>';
    return '<div class="rstars">' + s + "</div>";
  }
  function renderReviews() {
    var grid = document.getElementById("reviewGrid");
    if (!grid) return;
    grid.innerHTML = REVIEWS.map(function (r) {
      return '<article class="review-card">' +
        '<div class="review-card__top">' +
          '<div class="review-avatar" style="background:' + r.color + '">' + r.initial + '</div>' +
          '<div><p class="review-name">' + esc(r.name) + '</p><p class="review-when">' + esc(r.when) + '</p></div>' +
          '<i class="ti ti-brand-google review-g" aria-hidden="true"></i>' +
        '</div>' +
        starRow(r.rating) +
        '<p class="review-text">' + esc(r.text) + '</p>' +
      '</article>';
    }).join("");
    var note = document.getElementById("reviewsNote");
    if (note) note.innerHTML = 'These are sample reviews for the demo. When this goes live, this section pulls Katy Movers\u2019 real, current Google reviews automatically.';
  }
  renderReviews();

  // ── Info modal ──
  var modal = document.getElementById("infoModal");
  var howBuilt = document.getElementById("howBuiltLink");
  var modalClose = document.getElementById("infoModalClose");
  var modalBackdrop = document.getElementById("infoModalBackdrop");
  function openModal(e) { if (e) e.preventDefault(); modal.hidden = false; }
  function closeModal() { modal.hidden = true; }
  if (howBuilt) howBuilt.addEventListener("click", openModal);
  if (modalClose) modalClose.addEventListener("click", closeModal);
  if (modalBackdrop) modalBackdrop.addEventListener("click", closeModal);
  document.addEventListener("keydown", function (e) { if (e.key === "Escape") { closeModal(); } });
})();
